name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pip=22.3.1
  - requests=2.26.0
  - mlflow==2.1.1
  - scikit-learn=1.2
  - pandas=1.2.3
  - pip:
      - wandb==0.13.9
      - git+https://github.com/ThiagoGrabe/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
