name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.3.3
  - mlflow=1.14.1
  - scikit-learn=0.24.1
  - matplotlib=3.2.2
  - pillow=8.1.2
  - pandas=1.2.4
  - pip:
      - wandb==0.10.21
      - omegaconf==2.0.6
